# Generated by Django 4.1.7 on 2023-02-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('max_month_requests', models.PositiveSmallIntegerField(verbose_name='Максимум заявок в месяц')),
                ('max_response_time', models.PositiveSmallIntegerField(verbose_name='Время рассмотрения заявки(в часах)')),
                ('extra', models.CharField(max_length=350, verbose_name='Дополнительные возможности')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, verbose_name='Телеграм идентификатор')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('type', models.CharField(choices=[('employer', 'Заказчик'), ('freelancer', 'Фрилансер')], max_length=20, verbose_name='Тип пользователя')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
