# Generated by Django 4.1.7 on 2023-02-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='extra',
            field=models.CharField(blank=True, max_length=350, verbose_name='Дополнительные возможности'),
        ),
    ]
