# Generated by Django 4.1.7 on 2023-02-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_subscription_extra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Tariff',
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание заказа')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='backend.user', verbose_name='Исполнитель')),
            ],
        ),
    ]
