# Generated by Django 4.1.7 on 2023-02-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('ASSIGNED', 'Назначен исполнитель'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Готов')], default='CREATED', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
