# Generated by Django 4.1.7 on 2023-02-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_subscription_status_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(default=0, max_length=50, verbose_name='Логин исполнителя в телеграме'),
            preserve_default=False,
        ),
    ]
