# Generated by Django 4.1.7 on 2023-02-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Телеграм идентификатор'),
        ),
    ]
