# Generated by Django 4.1.7 on 2023-02-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to='backend.user', verbose_name='Заказчик'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_requests', to='backend.user', verbose_name='Исполнитель'),
        ),
    ]
