# Generated by Django 4.1.7 on 2023-02-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sent_requests',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество заявок'),
        ),
    ]
