# Generated by Django 4.1.7 on 2023-02-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_subscription_sent_requests'),
        ('backend', '0006_customer_worker_alter_request_customer_and_more'),
    ]

    operations = [
    ]
